
// icons.js – mapování Weatherbit ikon na vlastní ikonky
function getWeatherIcon(code) {
    const weatherCode = {
        "t01d": "Images/weather_thunderstorm_day.svg",
        "t01n": "Images/weather_thunderstorm_night.svg",
        "t02d": "Images/weather_thunderstorm_day.svg",
        "t02n": "Images/weather_thunderstorm_night.svg",
        "t03d": "Images/weather_thunderstorm_day.svg",
        "t03n": "Images/weather_thunderstorm_night.svg",
        "t04d": "Images/weather_thunderstorm.svg",
        "t04n": "Images/weather_thunderstorm.svg",
        "t05d": "Images/weather_thunderstorm.svg",
        "t05n": "Images/weather_thunderstorm.svg",
        "d01d": "Images/weather_drizzle.svg",
        "d01n": "Images/weather_drizzle.svg",
        "d02d": "Images/weather_drizzle.svg",
        "d02n": "Images/weather_drizzle.svg",
        "d03d": "Images/weather_drizzle.svg",
        "d03n": "Images/weather_drizzle.svg",
        "r01d": "Images/weather_light_rain.svg",
        "r01n": "Images/weather_light_rain.svg",
        "r02d": "Images/weather_light_rain.svg",
        "r02n": "Images/weather_light_rain.svg",
        "r03d": "Images/weather_light_rain.svg",
        "r03n": "Images/weather_light_rain.svg",
        "r04d": "Images/weather_light_rain.svg",
        "r04n": "Images/weather_light_rain.svg",
        "r05d": "Images/weather_heavy_rain.svg",
        "r05n": "Images/weather_heavy_rain.svg",
        "r06d": "Images/weather_heavy_rain.svg",
        "r06n": "Images/weather_heavy_rain.svg",
        "f01d": "Images/weather_freezing_rain.svg",
        "f01n": "Images/weather_freezing_rain.svg",
        "s02d": "Images/weather_heavy_snow.svg",
        "s02n": "Images/weather_heavy_snow.svg",
        "s03d": "Images/weather_heavy_snow.svg",
        "s03n": "Images/weather_heavy_snow.svg",
        "s04d": "Images/weather_heavy_snow_day.svg",
        "s04n": "Images/weather_heavy_snow_night.svg",
        "s05d": "Images/weather_sleet.svg",
        "s05n": "Images/weather_sleet.svg",
        "s06d": "Images/weather_medium_snow.svg",
        "s06n": "Images/weather_medium_snow.svg",
        "a01d": "Images/weather_fog.svg",
        "a01n": "Images/weather_fog.svg",
        "a02d": "Images/weather_fog.svg",
        "a02n": "Images/weather_fog.svg",
        "a03d": "Images/weather_haze.svg",
        "a03n": "Images/weather_haze.svg",
        "a04d": "Images/weather_dust.svg",
        "a04n": "Images/weather_dust.svg",
        "a05d": "Images/weather_fog.svg",
        "a05n": "Images/weather_fog.svg",
        "a06d": "Images/weather_fog.svg",
        "a06n": "Images/weather_fog.svg",
        "c01d": "Images/weather_clear_day.svg",
        "c01n": "Images/weather_clear_night.svg",
        "c02d": "Images/weather_light_cloudy_day.svg",
        "c02n": "Images/weather_light_cloudy_night.svg",
        "c03d": "Images/weather_heavy_cloudy_day.svg",
        "c03n": "Images/weather_heavy_cloudy_night.svg",
        "c04d": "Images/weather_cloudy.svg",
        "c04n": "Images/weather_cloudy.svg"
    };
    return weatherCode[code] || "Images/weather_unknown.svg";
}
